version: '3.8'

services:
  # LocalStack for AWS services simulation
  localstack:
    image: localstack/localstack:3.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,lambda,opensearch
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./localstack:/etc/localstack/init/ready.d"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - rag-network

  # Main FastAPI application
  rag-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
    volumes:
      - "./data:/app/data"
    depends_on:
      - localstack
    networks:
      - rag-network
    restart: unless-stopped

  # Streamlit frontend
  rag-frontend:
    build: .
    command: streamlit run frontend/streamlit_app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - rag-api
    networks:
      - rag-network
    restart: unless-stopped

networks:
  rag-network:
    driver: bridge